### ISSUE TITLE
Can't resolve '@bufbuild/protobuf'

### ISSUE THREAD

**Issue by nandorojo** [val-town/codemirror-codeium#34]
This package should either be a dependency, or devs should be told to download it in the docs. I think the former makes more sense, assuming it's getting used at runtime (which it appears to be)

**Comment by nandorojo** [comment]
Happy to PR this

**Comment by nandorojo** [comment]
#35 does this

**Comment by tmcw** [comment]
👍 Thanks, merged with a package-lock update and released: https://github.com/val-town/codemirror-codeium/releases/tag/v1.0.1
