### ISSUE TITLE
Accept suggestions on mobile

### ISSUE THREAD

**Issue by hatemhosny** [val-town/codemirror-codeium#7]
Great project 👍 
Thank you for open-sourcing this.

CodeMirror6 has great mobile support. I use it in [LiveCodes](https://github.com/live-codes/livecodes) (a client-side code playground for 80+ languages/frameworks) as the default editor on mobile.

Currently accepting suggestions requires hitting the tab button which is not available by default on mobile keyboards.
Would you consider adding additional key binding for accepting suggestions? May be "Enter" key.

**Comment by tmcw** [comment]
Yeah, good point - there should be a solution to this. Enter seems reasonable, but I'm not sure about adding Enter as a shortcut on desktop - it feels like there are situations where you're at

```ts
// Write a factorial function<cursor>
```

Where you want to hit Enter, but not accept a suggestion below.

**Comment by tmcw** [comment]
Yeah - that'll be somewhat harder to implement with the strategy in this plugin, but it's an option.

**Comment by hatemhosny** [comment]
> Yeah, good point - there should be a solution to this. Enter seems reasonable, but I'm not sure about adding Enter as a shortcut on desktop - it feels like there are situations where you're at
> 
> ```ts
> // Write a factorial function<cursor>
> ```
> 
> Where you want to hit Enter, but not accept a suggestion below.

I agree. On desktop we should stick to "tab" and not "Enter".

The other question is how to reject suggestions without "Esc" button. 
May be continue typing (not ideal) or click outside (as opposed to click on suggestion to accept).

**Comment by hatemhosny** [comment]
Another suggestion for rejecting suggestions on mobile is timing out.
e.g. if a suggestion was not accepted for e.g. 2 seconds, then it would disappear. 
Again, this behavior would only be on mobile.

**Comment by hatemhosny** [comment]
> I would expect that clicking on the suggestion would accept it on mobile

Clicking on the suggestion now works very well (#12). 
Also clicking outside (with the mouse) rejects suggestions.
Thank you.

However, I'm having trouble rejecting suggestions on touch screens. 
When I touch outside suggestion it is still accepted. The only way I can reject suggestion now is continue typing (sometimes this even doesn't reject and continue displacing the suggested text).
I have tried that on android phone and windows with touch screen.

Great work indeed.
I just thought it would be useful to report that.

**Comment by stevekrouse** [comment]
Closing this ticket because suggestions are now accepted on mobile.

The problem now is that they are *always* suggested, as @hatemhosny points out. New ticket for rejecting suggestions on mobile if the user clicks on any code except for the ghost text: https://github.com/val-town/codemirror-codeium/issues/43
